# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Plant Stuff
name: Zoë Van
description: >- # this means to ignore newlines until "baseurl:"
  TTS final project, involving Ruby, Airtable, Jekyll, and plants.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  zoevan

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "contrast"
search: true
pagination: 5
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Fetches the records from the specified base.
airtable:
  api_key: secret # Actually stored in _secret.yml
  tables:
    - name: plants # Base name
      app_id: appGhFman9206qELy # Airtable app ID found in the API documentation for your base
      sheets: 
        - name: plants # Table name
          view: Grid view # View name (default is Grid view)

airtable_pages:
  - table: plants # Table name as above
    type: plant # Singular of table name (removes "s")
    slug: title
    title: title
    name: title
    subdirectory: plants
    template: plants

collections:
  plants:
    output: true

defaults:
  - scope:
      path: "plants"
      type: "plants"
    values:
      layout: "single"
      collection: "plants"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
